### ISSUE TITLE
"ISSUEベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by sima9z** [sima9z/virtual_pet#64]
# 概要
以下はGitHubProjectのURLです。
https://github.com/users/sima9z/projects/2/views/1

# 実装予定の機能

- ペットのお世話をする機能（餌やり、水やり、掃除、散歩、遊ぶ）
- 時間経過でペットの状態を変化させる処理（状態によって適切なお世話の種類が変わる）
- ペットのアニメーション（クリック時、放置時、お世話をされた時）
- ペットのレベルアップ処理
- ペットの繫殖についての処理（レベルアップで繫殖する）
- 子供から大人への成長についての処理

# 必要なページ

- トップページ
- ログインページ
- ペットのカスタマイズページ
- メインページ

**Comment by sima9z** [comment]
お世話になっております。
お手数をおかけしますが、ご確認のほどよろしくお願いいたします。

以下はGitHubProjectのURLです。
[https://github.com/users/sima9z/projects/2](url)

**Comment by tarakish** [comment]
GitHub Projectはこのリポジトリに紐づけた状態に変更をお願いしますー！

**Comment by sima9z** [comment]
> GitHub Projectはこのリポジトリに紐づけた状態に変更をお願いしますー！

失礼いたしました。
紐づけいたしましたのでよろしくお願いいたします。

**Comment by tarakish** [comment]
確認できました👍
各Issueの説明がないものが見受けられるので、そのIssueでやるべきことをタスク化し、チェックボックスで羅列するように修正をお願いします！

**Comment by sima9z** [comment]
> 確認できました👍 各Issueの説明がないものが見受けられるので、そのIssueでやるべきことをタスク化し、チェックボックスで羅列するように修正をお願いします！

ご確認ありがとうございます。
承知いたしました。

全てのIssueにタスクを記述いたしました。

ご確認のほどよろしくお願いいたします。

**Comment by tarakish** [comment]
LGTMです！
MVPリリースに向けて開発頑張ってください。
