### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by sima9z** [sima9z/virtual_pet#88]
## 各種情報
サービス名: バーチャルペット フレンズ
サービスURL: https://virtual-pet-front.vercel.app/

### MVPリリース時
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 犬か猫の選択機能
- [x] ペットのお世話をする機能（餌やり、水やり、散歩）
- [x] ペットのアニメーション（放置時）
- [x] ペットのレベルアップ処理
- [x] 新規作成するペットに名前を付けられる機能
- [x] 子供から大人への成長についての処理

### 本リリース時
- [ ] 犬と猫の種類を追加
- [ ] ペットのに空腹値や体力の要素を追加
- [ ] 時間経過でペットの状態を変化させる処理（状態によって適切なお世話の種類が変わる）
- [ ] ペットのアニメーション（クリック時、お世話をされた時）
- [ ] パスワードリセット機能
- [ ] Line通知機能
- [ ] 育成中のペットの名前や見た目のカスタマイズ機能
- [ ] ペットの繫殖についての処理（レベルアップで繫殖する）
- [ ] ゲストでログイン機能
- [ ] Google認証機能

### 必要なページ
- [x] トップページ
- [ ] 遊び方の説明ページ
- [x] ログインページ
- [x] 新規ユーザー登録ページ
- [ ] パスワードリセット申請ページ
- [ ] パスワードリセット入力ページ
- [x] ペットの新規作成時のカスタマイズページ
- [ ] ペットの育成時のカスタマイズページページ
- [x] ペットのステータス表示ページ
- [x] メインページ
- [ ] お問い合わせ
- [ ] プライバシーポリシー
- [ ] 利用規約

####  トップページ
![Image](https://github.com/user-attachments/assets/13f76b45-04d1-496c-9246-164ebade3329)
#### ログインページ
![Image](https://github.com/user-attachments/assets/c95014b8-592b-41c4-b3c1-9266ec68b235)
#### 新規ユーザー登録ページ
![Image](https://github.com/user-attachments/assets/c07bc97f-0be6-40b0-a959-85029014ffe1)
#### ペットの新規登録ページ
![Image](https://github.com/user-attachments/assets/05f98c35-2c1a-4521-b2b0-9574b571704e)
#### メインページ
![Image](https://github.com/user-attachments/assets/56e96be1-9dfa-4316-96d5-0c6796c9c659)
#### ペットのステータス確認ウィンドウ
![Image](https://github.com/user-attachments/assets/542230c7-cdac-4bf4-8a5e-764a142b212a)

**Comment by sima9z** [comment]
お世話になっております。
54期Aクラス島津と申します。

卒業制作のMVPのレビューをお願いいたします。

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
LGTMです！
引き続き本リリースに向けて開発頑張ってください。
